import type { TimelineItem } from "../types/timeline";

// 手动编辑此文件，添加你的个人时间线条目
// 支持 type: "education" | "work" | "project" | "achievement"
// 不填 endDate 表示"进行中"，节点会有绿色脉冲动画

export const timelineData: TimelineItem[] = [
	{
		id: "byd",
		title: "比亚迪汽车工业有限公司",
		description: "一开始负责性能优化(算力优化、流畅性优化), 现在负责 android framework",
		type: "work",
		startDate: "2025-07-31",
		organization: "高级软件工程师",
		position: "深圳",
		skills: ["Linux 内核", "性能监控", "android"],
		// achievements: ["完成了 XX 项目", "获得了 XX 认证"],
		icon: "material-symbols:work",
		color: "#e80013",
		// featured: true,
	},
	{
		id: "scu",
		title: "四川大学",
		description: "进行计算机视觉相关研究，具体包括植物器官识别、缺陷检测",
		type: "education",
		startDate: "2022-09-01",
		endDate: "2025-06-30",
		organization: "硕士",
		position: "成都",
		skills: ["软件工程", "人工智能"],
		// achievements: ["获得学士学位", "GPA 3.8/4.0"],
		icon: "material-symbols:school",
		color: "#cf2712",
	},
	{
		id: "zzu",
		title: "郑州大学",
		description: "入门计算机，完成本科学习",
		type: "education",
		startDate: "2018-09-01",
		endDate: "2022-06-30",
		organization: "本科",
		position: "郑州",
		skills: ["软件工程", "后端开发"],
		// achievements: ["获得学士学位", "GPA 3.8/4.0"],
		icon: "material-symbols:school",
		color: "#263b3a",
	},
	{
		id: "yigao",
		title: "临颍一高",
		description: "记忆中的高中",
		type: "education",
		startDate: "2015-09-01",
		endDate: "2018-06-30",
		organization: "高中",
		position: "临颍县",
		skills: ["语数英", "物理化", "理综"],
		// achievements: ["获得学士学位", "GPA 3.8/4.0"],
		icon: "material-symbols:school",
		color: "#9a0000",
	},
	{
		id: "example-4",
		title: "示例：个人成就",
		description: "个人成就或里程碑条目。",
		type: "achievement",
		startDate: "2023-10-15",
		organization: "某竞赛",
		skills: ["算法", "数据结构"],
		achievements: ["获得三等奖", "提升了编程能力"],
		icon: "material-symbols:emoji-events",
		color: "#EA580C",
	},
	{
		id: "example-2",
		title: "示例：已完成的项目",
		description: "这是一条已完成的示例条目，有明确的起止日期。",
		type: "project",
		startDate: "2023-06-01",
		endDate: "2023-12-31",
		skills: ["Astro", "Tailwind CSS", "Svelte"],
		achievements: ["完成博客搭建", "上线个人主页"],
		links: [
			{ name: "GitHub", url: "https://github.com", type: "project" },
			{ name: "演示地址", url: "https://example.com", type: "website" },
		],
		icon: "material-symbols:code",
		color: "#7C3AED",
		featured: true,
	},
];
